/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradle.compat.v6;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'org.gradle.compat.v6.greeting' plugin.
 */
public class Gradle6CompatPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("org.gradle.compat.v6.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
